### ISSUE TITLE
Update ReadMe to Instruct to Run PowerShell as Admin

### ISSUE THREAD

**Issue by dperryazauditor** [azauditor/WinSysData#1]
We have found entities need to run as administrator to be able to pull the security policy. Item 3 of the ReadMe should be adjusted to read: 
3. Open PowerShell Console and run as administrator

**Comment by aentringer** [comment]
Handled via [commit e55ee18](https://github.com/azauditor/WinSysData/commit/e55ee18569ba91a3907f30ea0b0c4fddcafdd826). Script will now exit with an error if run without administrative privileges.
